# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\rnd\workspace\bank\appli\prodManager\ui\tabProject.ui'
#
# Created: Wed Sep 24 04:31:27 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_projectTab(object):
    def setupUi(self, projectTab):
        projectTab.setObjectName(_fromUtf8("projectTab"))
        projectTab.resize(628, 461)
        self.gridLayout = QtGui.QGridLayout(projectTab)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.line = QtGui.QFrame(projectTab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 0, 0, 1, 1)
        self.hlProd = QtGui.QHBoxLayout()
        self.hlProd.setObjectName(_fromUtf8("hlProd"))
        self.lProd = QtGui.QLabel(projectTab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lProd.setFont(font)
        self.lProd.setAlignment(QtCore.Qt.AlignCenter)
        self.lProd.setObjectName(_fromUtf8("lProd"))
        self.hlProd.addWidget(self.lProd)
        self.bCancelEdit = QtGui.QPushButton(projectTab)
        self.bCancelEdit.setMaximumSize(QtCore.QSize(50, 20))
        self.bCancelEdit.setObjectName(_fromUtf8("bCancelEdit"))
        self.hlProd.addWidget(self.bCancelEdit)
        self.bEditProd = QtGui.QPushButton(projectTab)
        self.bEditProd.setMaximumSize(QtCore.QSize(40, 20))
        self.bEditProd.setCheckable(True)
        self.bEditProd.setObjectName(_fromUtf8("bEditProd"))
        self.hlProd.addWidget(self.bEditProd)
        self.gridLayout.addLayout(self.hlProd, 1, 0, 1, 1)
        self.line_2 = QtGui.QFrame(projectTab)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 2, 0, 1, 1)
        self.hlDate = QtGui.QHBoxLayout()
        self.hlDate.setSpacing(2)
        self.hlDate.setObjectName(_fromUtf8("hlDate"))
        self.lStart = QtGui.QLabel(projectTab)
        self.lStart.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.lStart.setFont(font)
        self.lStart.setObjectName(_fromUtf8("lStart"))
        self.hlDate.addWidget(self.lStart)
        self.deStart = QtGui.QDateEdit(projectTab)
        self.deStart.setMinimumSize(QtCore.QSize(90, 0))
        self.deStart.setMaximumSize(QtCore.QSize(90, 16777215))
        self.deStart.setAlignment(QtCore.Qt.AlignCenter)
        self.deStart.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.deStart.setDate(QtCore.QDate(2014, 1, 1))
        self.deStart.setMinimumTime(QtCore.QTime(0, 0, 0))
        self.deStart.setCalendarPopup(True)
        self.deStart.setObjectName(_fromUtf8("deStart"))
        self.hlDate.addWidget(self.deStart)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.hlDate.addItem(spacerItem)
        self.lEnd = QtGui.QLabel(projectTab)
        self.lEnd.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.lEnd.setFont(font)
        self.lEnd.setObjectName(_fromUtf8("lEnd"))
        self.hlDate.addWidget(self.lEnd)
        self.deEnd = QtGui.QDateEdit(projectTab)
        self.deEnd.setMinimumSize(QtCore.QSize(90, 0))
        self.deEnd.setMaximumSize(QtCore.QSize(90, 16777215))
        self.deEnd.setAlignment(QtCore.Qt.AlignCenter)
        self.deEnd.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.deEnd.setDate(QtCore.QDate(2014, 1, 1))
        self.deEnd.setCalendarPopup(True)
        self.deEnd.setObjectName(_fromUtf8("deEnd"))
        self.hlDate.addWidget(self.deEnd)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hlDate.addItem(spacerItem1)
        self.gridLayout.addLayout(self.hlDate, 3, 0, 1, 1)
        self.line_3 = QtGui.QFrame(projectTab)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 4, 0, 1, 1)
        self.hlWorkDir = QtGui.QHBoxLayout()
        self.hlWorkDir.setSpacing(2)
        self.hlWorkDir.setObjectName(_fromUtf8("hlWorkDir"))
        self.lWorkDir = QtGui.QLabel(projectTab)
        self.lWorkDir.setMinimumSize(QtCore.QSize(88, 0))
        self.lWorkDir.setMaximumSize(QtCore.QSize(88, 16777215))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.lWorkDir.setFont(font)
        self.lWorkDir.setObjectName(_fromUtf8("lWorkDir"))
        self.hlWorkDir.addWidget(self.lWorkDir)
        self.leWorkDir = QtGui.QLineEdit(projectTab)
        self.leWorkDir.setMinimumSize(QtCore.QSize(400, 0))
        self.leWorkDir.setMaximumSize(QtCore.QSize(280, 16777215))
        self.leWorkDir.setObjectName(_fromUtf8("leWorkDir"))
        self.hlWorkDir.addWidget(self.leWorkDir)
        self.bOpenWorkDir = QtGui.QPushButton(projectTab)
        self.bOpenWorkDir.setMaximumSize(QtCore.QSize(40, 20))
        self.bOpenWorkDir.setObjectName(_fromUtf8("bOpenWorkDir"))
        self.hlWorkDir.addWidget(self.bOpenWorkDir)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hlWorkDir.addItem(spacerItem2)
        self.gridLayout.addLayout(self.hlWorkDir, 5, 0, 1, 1)
        self.line_5 = QtGui.QFrame(projectTab)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout.addWidget(self.line_5, 6, 0, 1, 1)
        self.splitter_2 = QtGui.QSplitter(projectTab)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.qfParams = QtGui.QFrame(self.splitter_2)
        self.qfParams.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.qfParams.setFrameShape(QtGui.QFrame.StyledPanel)
        self.qfParams.setObjectName(_fromUtf8("qfParams"))
        self.hlParams = QtGui.QHBoxLayout(self.qfParams)
        self.hlParams.setSpacing(0)
        self.hlParams.setMargin(0)
        self.hlParams.setObjectName(_fromUtf8("hlParams"))
        spacerItem3 = QtGui.QSpacerItem(200, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hlParams.addItem(spacerItem3)
        spacerItem4 = QtGui.QSpacerItem(200, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hlParams.addItem(spacerItem4)
        spacerItem5 = QtGui.QSpacerItem(200, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hlParams.addItem(spacerItem5)
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setMinimumSize(QtCore.QSize(0, 0))
        self.splitter.setFrameShape(QtGui.QFrame.StyledPanel)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.verticalLayoutWidget = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.vlProdTree = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.vlProdTree.setSpacing(0)
        self.vlProdTree.setMargin(0)
        self.vlProdTree.setObjectName(_fromUtf8("vlProdTree"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.vlProdStep = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.vlProdStep.setSpacing(0)
        self.vlProdStep.setMargin(0)
        self.vlProdStep.setObjectName(_fromUtf8("vlProdStep"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.vlProdAttr = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.vlProdAttr.setSpacing(0)
        self.vlProdAttr.setMargin(0)
        self.vlProdAttr.setObjectName(_fromUtf8("vlProdAttr"))
        self.gridLayout.addWidget(self.splitter_2, 7, 0, 1, 1)

        self.retranslateUi(projectTab)
        QtCore.QMetaObject.connectSlotsByName(projectTab)

    def retranslateUi(self, projectTab):
        projectTab.setWindowTitle(_translate("projectTab", "Tab Project", None))
        self.lProd.setText(_translate("projectTab", "Project Name (Alias)", None))
        self.bCancelEdit.setText(_translate("projectTab", "Cancel", None))
        self.bEditProd.setText(_translate("projectTab", "Edit", None))
        self.lStart.setText(_translate("projectTab", "Project Start: ", None))
        self.deStart.setDisplayFormat(_translate("projectTab", "yyyy/MM/dd", None))
        self.lEnd.setText(_translate("projectTab", "Project End: ", None))
        self.deEnd.setDisplayFormat(_translate("projectTab", "yyyy/MM/dd", None))
        self.lWorkDir.setText(_translate("projectTab", "Project Work Dir:", None))
        self.bOpenWorkDir.setText(_translate("projectTab", "Open", None))

